name: Fuzz Parser

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - src/scanner.c
      - .github/workflows/fuzz.yml
  pull_request:
    paths:
      - src/scanner.c
      - .github/workflows/fuzz.yml

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run fuzzer
        uses: tree-sitter/fuzz-action@6a1dcff00aefd038ba418bd63732a9add4901266 # v4
